
name:                render-latex-template
version:             "0.1.0"
license:             MIT
license-file:        LICENSE
author:              Max Taldykin
maintainer:          jorpic@gmail.com
category:            Text


dependencies:
  - aeson
  - base
  - configurator
  - directory
  - ede
  - filepath
  - lens
  - process
  - text
  - unordered-containers


default-extensions:
  - OverloadedStrings
  - LambdaCase
  - RecordWildCards


ghc-options:
  - -Wall
  - -threaded
  - -O2
  - -funbox-strict-fields


executables:
  rlt:
    source-dirs: src
    main: Main.hs
