resolver: lts-7.8

packages:
  - '.'
  - location:
      git: git@github.com:jorpic/fsutils
      commit: HEAD


extra-deps:
  - guid-0.1.0

flags: {}

extra-package-dbs: []

image:
  containers:
    - base: "fpco/stack-run"
